-- 49.
SELECT e.FIRST_NAME, e.LAST_NAME, to_char(e.HIRE_DATE, 'IW-YYYY') as Einstelldatum FROM EMPLOYEES e ORDER BY e.HIRE_DATE;
-- 50.
SELECT TO_CHAR(e.HIRE_DATE, 'YYYY'), COUNT(*) FROM EMPLOYEES e GROUP BY TO_CHAR(e.HIRE_DATE, 'YYYY') ORDER BY TO_CHAR(e.HIRE_DATE, 'YYYY');
-- 51.
SELECT e.FIRST_NAME, e.LAST_NAME, e.PHONE_NUMBER, substr(e.FIRST_NAME, 1, 1) || substr(e.LAST_NAME, 1, 1) || substr(e.PHONE_NUMBER, length(e.PHONE_NUMBER) - 3, 4) FROM EMPLOYEES e;
-- 52.
SELECT e.EMPLOYEE_ID || rpad('*', ROUND(e.SALARY/500) ,'*') FROM EMPLOYEES e;
-- 53.
SELECT substr(e.LAST_NAME, 1, 1), COUNT(*) FROM EMPLOYEES e GROUP BY substr(e.LAST_NAME, 1, 1) ORDER BY substr(e.LAST_NAME, 1, 1);
-- 54.
SELECT FIRST_NAME, LAST_NAME,
       CASE WHEN e.SALARY < 4000 THEN
            'LOW'
        WHEN e.SALARY < 8000 THEN
            'MEDIUM'
        ELSE
            'HIGH'
        END
       FROM EMPLOYEES e;
-- 55.
SELECT D.DEPARTMENT_ID, NVL(AVG(SALARY), 0) as Durchschnittsgehalt FROM EMPLOYEES e RIGHT JOIN DEPARTMENTS D on e.DEPARTMENT_ID = D.DEPARTMENT_ID GROUP BY D.DEPARTMENT_ID;
-- 56.
SELECT EMPLOYEE_ID, FIRST_NAME, LAST_NAME FROM EMPLOYEES e CONNECT BY PRIOR MANAGER_ID = EMPLOYEE_ID START WITH EMPLOYEE_ID = 115;