-- 67.
ALTER TABLE PROJEKTE
    ADD CONSTRAINT PK_PROJEKT PRIMARY KEY (Projektnummer);

ALTER TABLE PROJEKTMITARBEIT
    ADD (
        CONSTRAINT FK_PROJEKTMITARBEIT FOREIGN KEY (EMPLOYEE_ID) REFERENCES EMPLOYEES (EMPLOYEE_ID),
        CONSTRAINT PK_PROJEKTMITARBEIT PRIMARY KEY (Projektnummer, EMPLOYEE_ID)
        );