-- 11.
SELECT SUM(SALARY), AVG(SALARY) FROM EMPLOYEES;
-- 12.
SELECT AVG(SALARY), MIN(SALARY), MAX(SALARY) FROM EMPLOYEES WHERE DEPARTMENT_ID = 80;
-- 13.
SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID ORDER BY COUNT(EMPLOYEE_ID) DESC;
-- 14.
SELECT DEPARTMENT_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
-- 15.
SELECT JOB_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES GROUP BY JOB_ID HAVING COUNT(EMPLOYEE_ID) > 9;
-- 16.
SELECT DEPARTMENT_ID, AVG(SALARY), MAX(SALARY), MIN(SALARY) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
-- 17.
SELECT REGION_ID, COUNT(COUNTRY_ID) FROM COUNTRIES GROUP BY REGION_ID;
-- 18.
SELECT LOCATION_ID, COUNT(DEPARTMENT_ID) FROM DEPARTMENTS GROUP BY LOCATION_ID;
-- 19.
SELECT COUNTRY_ID, COUNT(LOCATION_ID) FROM LOCATIONS GROUP BY COUNTRY_ID;
-- 20.
SELECT MANAGER_ID, COUNT(EMPLOYEE_ID) FROM EMPLOYEES WHERE DEPARTMENT_ID = 50 AND MANAGER_ID != 100 GROUP BY MANAGER_ID;
-- 21.
SELECT DEPARTMENT_ID, AVG(SALARY)*100/MAX(SALARY) AS "%" FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
-- 22.
SELECT MAX(AVG(SALARY)) FROM EMPLOYEES GROUP BY DEPARTMENT_ID;
-- 23.
SELECT EMPLOYEE_ID FROM JOB_HISTORY GROUP BY EMPLOYEE_ID HAVING COUNT(JOB_ID) >= 2;