-- 33.
SELECT DEPARTMENT_NAME, CITY FROM DEPARTMENTS d, LOCATIONS l WHERE d.LOCATION_ID(+) = l.LOCATION_ID;
-- 34.
SELECT a.* FROM EMPLOYEES a, EMPLOYEES b WHERE b.FIRST_NAME = 'Douglas' AND b.LAST_NAME = 'Grant' AND a.SALARY = b.SALARY;
-- 35.
SELECT a.LAST_NAME Mitarbeiter, b.LAST_NAME Vorgesetzter FROM EMPLOYEES a, EMPLOYEES b WHERE a.MANAGER_ID = b.EMPLOYEE_ID;
-- 36.
SELECT a.* FROM EMPLOYEES a, EMPLOYEES b WHERE a.MANAGER_ID = b.EMPLOYEE_ID AND a.SALARY > b.SALARY;