-- 24.
SELECT FIRST_NAME, LAST_NAME, CITY FROM EMPLOYEES, LOCATIONS, DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID;
-- 25.
SELECT CITY, COUNT(DEPARTMENT_ID) FROM DEPARTMENTS, LOCATIONS WHERE DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID GROUP BY CITY;
-- 26.
SELECT COUNTRY_NAME, COUNT(LOCATION_ID) FROM COUNTRIES, LOCATIONS LOC WHERE COUNTRIES.COUNTRY_ID = LOC.COUNTRY_ID GROUP BY COUNTRY_NAME;
-- 27.
SELECT EMPLOYEES.* FROM EMPLOYEES, DEPARTMENTS WHERE DEPARTMENT_NAME = 'Sales' AND DEPARTMENTS.DEPARTMENT_ID = EMPLOYEES.DEPARTMENT_ID;
-- 28.
SELECT DEPARTMENTS.* FROM DEPARTMENTS, LOCATIONS, COUNTRIES, REGIONS WHERE LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID AND COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID AND REGIONS.REGION_NAME = 'Europe' AND REGIONS.REGION_ID = COUNTRIES.REGION_ID;
-- 29.
SELECT DEPARTMENT_NAME, SUM(SALARY) FROM EMPLOYEES, DEPARTMENTS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID GROUP BY DEPARTMENT_NAME;
-- 30.
SELECT REGION_NAME, COUNT(COUNTRY_ID) as "Anzahl" FROM REGIONS, COUNTRIES WHERE REGIONS.REGION_ID = COUNTRIES.REGION_ID GROUP BY REGION_NAME;
-- 31.
SELECT DISTINCT JOB_TITLE, REGION_NAME FROM EMPLOYEES, JOBS, REGIONS, DEPARTMENTS, LOCATIONS, COUNTRIES WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND EMPLOYEES.JOB_ID = JOBS.JOB_ID AND LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID AND COUNTRIES.COUNTRY_ID = LOCATIONS.COUNTRY_ID AND REGIONS.REGION_ID = COUNTRIES.REGION_ID ORDER BY REGION_NAME;
-- 32.
SELECT CITY, AVG(SALARY) FROM EMPLOYEES, DEPARTMENTS, LOCATIONS WHERE EMPLOYEES.DEPARTMENT_ID = DEPARTMENTS.DEPARTMENT_ID AND LOCATIONS.LOCATION_ID = DEPARTMENTS.LOCATION_ID GROUP BY CITY;