-- 46.
SELECT EMPLOYEE_ID FROM EMPLOYEES INTERSECT SELECT EMPLOYEE_ID FROM JOB_HISTORY;
-- 47.
SELECT DEPARTMENT_ID FROM DEPARTMENTS MINUS SELECT DEPARTMENT_ID FROM EMPLOYEES;
-- 48.
SELECT CITY FROM LOCATIONS MINUS SELECT DISTINCT CITY FROM DEPARTMENTS, LOCATIONS WHERE DEPARTMENTS.LOCATION_ID = LOCATIONS.LOCATION_ID;