-- 64.
ALTER TABLE EMPLOYEES ADD URLAUBSTAGE NUMBER;
-- 65.
CREATE TABLE PROJEKTE
(
    Projektnummer NUMBER,
    Bezeichnung   VARCHAR(255)
);

CREATE TABLE PROJEKTMITARBEIT
(
    Projektnummer NUMBER,
    EMPLOYEE_ID   NUMBER
);

INSERT INTO PROJEKTE (Projektnummer, Bezeichnung)
VALUES (1, 'SQL Datenbank aufsetzen'),(2, 'SQL Abfragen erstellen');

INSERT INTO PROJEKTMITARBEIT(Projektnummer, EMPLOYEE_ID)
VALUES (1, 100),(1, 101),(1, 102),(2, 103),(2, 104),(2, 102),(2, 101);
-- 66.
CREATE TABLE DEPARTMENT_LOCATIONS AS (
    SELECT DEPARTMENT_ID, LOCATION_ID
    FROM DEPARTMENTS
);